### ISSUE TITLE
about filght-dataset

### ISSUE THREAD

**Issue by heiwa0519** [utiasDSL/utias_uwb_dataset#1]
In filght dataset, how can I obtain SNR，Pd and other information, which shown in identification dataset?

**Comment by Williamwenda** [comment]
Hi, heiwa. Unfortunately, we didn't collect the SNR, Power Difference, and other information during the flight test. In retrospect, it would be interesting to collect those info. during the NLOS flight testing trials. The following code might be helpful if you have a Crazyflie with an UWB tag and several anchors and wish to collect those by yourself.

```
  dwGetData(dev, (uint8_t*)&rxPacket, dataLength);
  const uint8_t anchorId = rxPacket.sourceAddress & 0xff;
  // get the (1) first path power:              FP_POWER,
  //         (2) total received power:          RX_POWER,
  //     and (3) FP Amplitude / CIRE noiseStd:  snr
  float RX_POWER = 0.0f;    // received power
  float FP_POWER = 0.0f;    // first path power
  FP_POWER = dwGetFirstPathPower(dev);
  RX_POWER = dwGetReceivePower(dev);
  if(anchorId==(uint8_t)1)
  {
      log_snr_1 = dwGetReceiveQuality(dev);
      log_powerdiff_1 = RX_POWER - FP_POWER;
  }
  else if (anchorId==(uint8_t)2)
  {
      log_snr_2 = dwGetReceiveQuality(dev);
      log_powerdiff_2 = RX_POWER - FP_POWER;
  }
```
Note, the "1" and "2" are the anchor ids I set for the identification dataset. You might wish to change them based on your purpose. Adding the above code into "lpsTdoa2Tag.c" or "lpsTdoa3Tag.c" on the crazyflie firmware will enable you to access the SNR,  first path power,  total received power, and power difference values. Hope you will find this information helpful. :)

**Comment by Williamwenda** [comment]
Issue closed due to no further comments received.
